apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: result-pod
      labels:
        name: votingresults-pod
        app: demo-voting-app
    spec:
      containers:
        - name: votingresults-pod
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: votingresults-pod
      app: demo-voting-app

