apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  template:
    metadata:
      name: voting-pod
      labels:
        name: votingapp-pod
        app: demo-voting-app
    spec:
      containers:
        - name: votingapp-pod
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: votingapp-pod
      app: demo-voting-app

